version: '3.9'

services:
  flask-app:
    container_name: flask-app
    image: flask-app
    build: .
    ports:
      - "80:80"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db1:5432/postgres
      - TEST_DATABASE_URL=postgresql://postgres:postgres@db_test:5432/postgres
      - FLASK_ENV=development
    depends_on:
      - db1

  db1:
    container_name: db1
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

  db_test:
    container_name: db_test
    image: postgres:12
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    volumes:
      - pgtestdata:/var/lib/postgresql/data


volumes:
  pgdata: {}
  pgtestdata: {}
